// Regenerates ../assets/js/teams.js from ESPN team lists (fetched by curl; ESPN sends no CORS header).
import fs from 'node:fs';
const src = [
  ['nfl', 'football_nfl.json', 'NFL'],
  ['nba', 'basketball_nba.json', 'NBA'],
  ['mlb', 'baseball_mlb.json', 'MLB'],
  ['nhl', 'hockey_nhl.json', 'NHL'],
  ['mls', 'soccer_usa.1.json', 'MLS'],
  ['cfb', 'football_cfb.json', 'College Football'],
  ['cbb', 'basketball_mens-college-basketball.json', 'College Basketball'],
];
const FBS = new Set(JSON.parse(fs.readFileSync(new URL('fbs-ids.json', import.meta.url))));
// D-I college basketball is 362 teams; kept to the same ~68 Power 4 football schools already
// tracked (tools/scout/p4-ids.json) so the list stays a size fans can actually pick from.
// ESPN team ids are shared across a school's sports, so the football P4 ids apply directly.
const CBB = new Set(JSON.parse(fs.readFileSync(new URL('cbb-ids.json', import.meta.url))));
const out = [];
for (const [lg, file] of src) {
  const j = JSON.parse(fs.readFileSync(new URL(file, import.meta.url)));
  const teams = j.sports[0].leagues[0].teams.map(t => t.team);
  for (const t of teams) {
    if (t.isActive === false) continue;
    if (lg === 'cfb' && !FBS.has(String(t.id))) continue;
    if (lg === 'cbb' && !CBB.has(String(t.id))) continue;
    const logo = (t.logos || []).find(l => (l.rel || []).includes('default')) || (t.logos || [])[0];
    out.push({
      id: lg === 'cfb' || lg === 'cbb' ? `${lg}-${t.id}` : `${lg}-${t.abbreviation.toLowerCase()}`,
      lg,
      eid: String(t.id),
      name: t.displayName,
      short: t.shortDisplayName || t.name,
      loc: t.location,
      abbr: t.abbreviation,
      color: t.color ? '#' + t.color : '#444444',
      logo: logo ? logo.href : '',
    });
  }
  console.log(lg, out.filter(t => t.lg === lg).length);
}
const ids = new Set(); for (const t of out) { if (ids.has(t.id)) t.id += '-' + t.logo.match(/\/(\w+)\.png/)?.[1]; ids.add(t.id); }
const leagues = Object.fromEntries(src.map(([k, , n]) => [k, n]));
fs.writeFileSync(new URL('../assets/js/teams.js', import.meta.url),
  `// Generated by tools/build-teams.mjs from ESPN's team lists. Do not hand-edit.\n` +
  `export const LEAGUES = ${JSON.stringify(leagues)};\n` +
  `export const TEAMS = [\n${out.map(t => '  ' + JSON.stringify(t)).join(',\n')}\n];\n` +
  `export const TEAM_BY_ID = Object.fromEntries(TEAMS.map(t => [t.id, t]));\n`);
console.log('total', out.length);
